
services:
  # Hub Mercure
  mercure:
    image: dunglas/mercure:v0.15
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'your-256-bit-secret-key-here-change-this-in-production'
      MERCURE_SUBSCRIBER_JWT_KEY: 'your-256-bit-secret-key-here-change-this-in-production'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3000 http://localhost:8000
        anonymous
        subscriptions
        publish_origins http://localhost:8000
    ports:
      - "3001:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - app_network

  # API Symfony
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3001/.well-known/mercure
      MERCURE_JWT_SECRET: 'your-256-bit-secret-key-here-change-this-in-production'
    ports:
      - "8000:80"
    depends_on:
      - mercure
    volumes:
      - ./:/var/www/html
    networks:
      - app_network

volumes:
  mercure_data:
  mercure_config:


networks:
  app_network:
